### ISSUE TITLE
endpoints.TweetActivity Not Found

### ISSUE THREAD

**Issue by cometothed4rkside** [Sinkmanu/TwitterAccountBlocker#3]
[*] Guest_id: v1%3A170392141048529414
Traceback (most recent call last):
  File "C:\Users\xxxxx\Desktop\TwitterAccountBlocker-main\TwitterAccountBlocker.py", line 223, in <module>
    authorization_bearer,guest_token,rt_path,viewer_path = getTokens()
  File "C:\Users\xxxxx\Desktop\TwitterAccountBlocker-main\TwitterAccountBlocker.py", line 34, in getTokens
    tweetActivity_endpoint = re.findall(r'"endpoints.TweetActivity":"(.*)",', r.text, re.IGNORECASE)[0].split("\"")[0]
IndexError: list index out of range

**Comment by Sinkmanu** [comment]
Fixed! Twitter (X) has modified the "endpoints" and They have also added some fields to the json.

**Comment by cometothed4rkside** [comment]
Yes the problem is solved and it works great. Additionally, cookies can be saved at login and used at the next login.

**Comment by Sinkmanu** [comment]
Yes, It is not hard to do; but the problem is that it is a CLI program (additionally to an example script).). I develop this with the purpose to explain how to do web scraping and [create an API ](https://unam.re/blog/developing-your-own-twitter-api)of wathever web application.
The cookies could be saved in a file, but this could be a security concern, if someone get this file could access to your account.

You could modify easily the code in order to use the cookies instead the user/password. Save the `authentication_bearer` `auth_token` and `guest_token` and modify the following:

```
    if ((args.username is not None) and (args.tweet_id is not None)):
        #password = args.password
        #if password is None:
        #    password = getpass.getpass(prompt='Password: ')
        #authorization_bearer,guest_token,rt_path,viewer_path = getTokens()
        #auth_token = login(authorization_bearer, guest_token, args.username, password, args.email)
        guest_token = <your guest_token>
        auth_token =  <your auth_token>
        authorization_bearer =  <your authentication bearer>
        csrf_token = getCSRFToken(guest_token, auth_token, authorization_bearer)
        users_rt = getRetweets(args.tweet_id, csrf_token, auth_token, authorization_bearer)
        for i in users_rt:
            blockAccount(i, auth_token, csrf_token, authorization_bearer)
    else:
        parser.print_help()
```
