### ISSUE TITLE
KeyError: 'flow_token'

### ISSUE THREAD

**Issue by cometothed4rkside** [Sinkmanu/TwitterAccountBlocker#5]
[*] Guest_id: v1%3A170400363755xx9xx64
[*] endpoints.TweetActivity: 41ed457
[*] Js with Bearer token: https://abs.twimg.com/responsive-web/client-web/main.3c06e8ca.js
[*] Guest token: 17413435xxx92043983
[*] Bearer:  AAAAAAAAAAAAAAAAAxxxxRILgAAAAAAnNwIzUejRCOuH5xxxxfk8LF81IUq16xxxx4FA33xxxxWjCpTnA
[*] Guest token: 17xxxx5899xxx1606
[*] url_retweet_endpoint: https://abs.twimg.com/responsive-web/client-web/shared~bundle.TweetEditHistory~bundle.QuoteTweetActivity~bundle.TweetActivity.41ed457a.js
[*] rt_url: sOBhVxxxx4XGexxxxpHlg
[*] flow_token: g;170400363993211117:-1704003639935:n41yxxxxI1bfALwxxxIPZZ:0
[*] flow_token: g;170400363993211117:-1704003639935:n41xxxxxxMI1bfALwveIPZZ:1
[*] flow_token: g;170400363993211117:-1704003639935:n41xxxxI1bfAxxxeIPZZ:6

Traceback (most recent call last):
  File "block.py", line 229, in <module>
    auth_token = login(authorization_bearer, guest_token, args.username, password, args.email)
  File "block.py", line 112, in login
    flow_token = json.loads(r.text)['flow_token']
KeyError: 'flow_token'

**Comment by Sinkmanu** [comment]
Hello, I have tried and the script still working. Could you add a print before line 112?  This is the step in the "flow" where you send the email or username. I think that Twitter (X) is blocking you the login with username, thus, you need use the email.
Anyway If you want to see the error message, add this line to the code:
```
111        r = requests.post(url_flow_2, verify=False, headers=user_agent, data=json.dumps(data))
112        print(r.text)
113        flow_token = json.loads(r.text)['flow_token']
```

**Comment by deepakstark01** [comment]
<img width="978" alt="Image" src="https://github.com/user-attachments/assets/18e647ba-1ff1-4ebf-bf6e-52312487e87f" />

getting same issue
